[template]
variables = ["project_name"]

[template.variables.project_name]
description = "The name of the project"
default = "my_project"

[template.placeholders]
project_name = { type = "string", prompt = "Enter the project name" }
