[template.variables]
project_name = { description = "The name of the project", default = "my_project" }
package_name = { description = "The name of the package", default = "com.coraool.digiplus" }
project_class = { description = "The name of the project class", default = "Dgug" }
server_port = { description = "The port of the server", default = "8080" }

[template.placeholders]
project_name = { type = "string", prompt = "Enter the project name" }
package_name = { type = "string", prompt = "Enter the package name" }
project_class = { type = "string", prompt = "Enter the project class" }
server_port = { type = "string", prompt = "Enter the server port" }
